apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  namespace: servicetrips-frontend
resources:
  - ../base
  - versions-config-cm.yaml
  - versions-title-cm.yaml
  - versions-route.yaml
patches:
  - path: deploy.yaml
