apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/instance: servicetrips-version
    orebroll.se/tls-acme: "true"
  name: servicetrips-version-cert
  namespace: servicetrips-frontend
spec:
  dnsNames:
  - servicetrips-version.cloud-dev.orebroll.se
  duration: 2160h0m0s
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: orebroll-ca
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  renewBefore: 1440h0m0s
  secretName: servicetrips-version-cert
  secretTemplate:
    annotations:
      letsencrypt.io/tls-acme: "true"
    labels:
      letsencrypt.io/tls-acme: "true"
  subject:
    organizations:
    - Region Orebro lan
  usages:
  - server auth
  - client auth
  - digital signature
  - key encipherment
status: {}